script:

  ######################################################
  # Pre-requisites #####################################
  ######################################################

  # Install Ballerina which is reuqired to run automated integration tests
  - BALLERINA_VERSION=${VERSION:-0.990.2}
  - echo -e "\033[36m${BALLERINA_VERSION}\033[m"

  - DISTRIBUTION_NAME=ballerina-${BALLERINA_VERSION}
  - echo -e "\033[36m${DISTRIBUTION_NAME}\033[m"

  - DOWNLOAD_CHANNEL=${CHANNEL:-downloads}
  - echo -e "\033[36m${DOWNLOAD_CHANNEL}\033[m"

  - DOWNLOAD_LOCATION=${URL:-https://product-dist.ballerina.io}
  - echo -e "\033[36m${DOWNLOAD_LOCATION}\033[m"

  - echo -e "\033[36m${DOWNLOAD_LOCATION}/${DOWNLOAD_CHANNEL}/${BALLERINA_VERSION}${RC:-}/${DISTRIBUTION_NAME}${RC:-}.zip\033[m"
  - wget ${DOWNLOAD_LOCATION}/${DOWNLOAD_CHANNEL}/${BALLERINA_VERSION}${RC:-}/${DISTRIBUTION_NAME}${RC:-}.zip

  - unzip -q ${DISTRIBUTION_NAME}${RC:-}.zip

  - export PATH=${PATH}:$(pwd)/${DISTRIBUTION_NAME}/bin

  - ballerina version

  ######################################################
  # Staging environment ################################
  ######################################################

  - export ENV=Staging
  # build the artefacts and deploy in staging server
  - mvn clean install -q
  - cd SampleServicesCompositeApplication$ENV
  - mvn clean deploy -Dmaven.deploy.skip=true -Dmaven.car.deploy.skip=false
  - cd ../
  # run the integration tests
  - cd IntegrationTests
  - ballerina test 

  ######################################################
  # Production environment ################################
  ######################################################

  - export ENV=Production

env:
  global:
  - secure: BEo6kfbc7ZcVeKidDKNkli4LERgayKiaJ5xeBCFfoXiIIZWOHaA2OzNkC425buxv9kCGifnkJlfsAe3fqlscajuHyLYFf7noHsoQ163HOmG0VE4ZAu0Y1flMn/0kP5oU4dbQjHUHxcpTwFR6eIx5XK7yV7swmutLYNqZ9eg1q8DZCl5bRwktkMr0NAMMXEodFI0Hot0XdA8huDI+c+PfJZT3YU7QhPXLaqWlADV/RAo3sn/1kjrtQI1MKNtpyr/wwFMa9nckQoxUBBEPBVxOe8m+38+5oZPUm9GcaaIsydeRlQILHrNJiKA1KqQcRaXynlPU2A9HoxoLS80gdkMzYd+iCcMTyfK43JikuWGvaoJzTBuBYXE6jr61Mya46boSVP+uGatlq6iIq75V3JXnVeY+dLTDdnxT2JLPd1AyUAbOxBVi1w4lX4DxZ3ayXHJ72nMwAAGcxAjQhmXJeJPt/EGajxsjbe2EAJ0XT2Mh5u/XPIAX/da6Ynt9Xej67OpJAZINm08JUkCVtEHgFNkUKU0vCAfAdLWnzp28BQhERObhdBS4nw3VxbR3tioVueQRwOhwD3DNIKadJVN083c5aQmKcmkwOHji4xmIFwXPjgj3+SONg/iHwBcot8nz16FD5N9566U7FXCMvj+xZy1Qdtkq0Gr+EMV/0zm+rebvpLI=
  - secure: jhasFLdCKNktPpt3KbNqSlAwXdya1eHhUj+MVS6wG5yz27NElUheEJhwIFaoBRL5f4ragg/8nDIoGBCKEWQ40lYzeB8+RyK3EswRAaRPa7q7F6QOUTVvp0kUlFoEh6zlj07URyDRP/qAxc8mcS4WP3FvDLF+zmRsaxvuwf1In6IjLdaD8ZHA8/74+dAkWd/Qj2oYKM04qS5G1jcRu4nyo5IzcAV5oJPJtnqwutJ5k91D3nno0XcbTeFYuUHfUIKOx/bs8xHauelSlmO0RvYmJ962pY+ALI4q65wWdY2g5yDmt1KIj8SQCuOexBXYLdteDqgTL4jmwy5OR42Xu251HJc6YxQ7R3n38+2gJrc7g3wWMp7KuByym4Jfzlm2pZGCVBhi20K85Ax/i8eB6AX2J4KwXFKQPFCYRAPDxsEEMtvXw5ZhwMnhMCuyCgU84g15jN6q16ahovH2F7cCD1SxfD0KXIDl1eGQfYOk+1jeK9+BIR4nuEUVa0j9SEHH4cCXrWYAxTNoNvAHNGgeXl9k6LOCpfS9lCnrCut2tqXatvwIIXzF6WaYDhMdx5Ob2Av5J/EDd1YVa3Dp2ZvEdKSlKIXnzIl9KUtAjwq1Gos0Kp1tLLyvRYM0q4iU9qW7gJFPYmunlpdSHb8c707ndj4+6yI6kuOzTOBYxHeFH+IEbys=